### ISSUE TITLE
Upgrading to 1.6.x from 1.5.x throws mysterious exceptions: undefined method `find_by_identifier'

### ISSUE THREAD

**Issue by tadman** [comfy/comfortable-mexican-sofa#138]
When upgrading to 1.6.x from 1.5.x or earlier you will get an exception that looks roughly like:

```
undefined method `find_by_identifier' for #<Class:0x00000104e84f18>
```

This can be fixed by adding the "160" migration, but the process for this is manual:

```
rails generate migration upgrade_to_160
```

The resulting file should be replaced with the contents of [the 160 migration](https://raw.github.com/comfy/comfortable-mexican-sofa/master/db/upgrade_migrations/07_upgrade_to_1_6_0.rb) listed in the Wiki.

It would be nice if an error message indicating where to start was displayed rather than simply exploding and leaving it up to the user to discern what went wrong. Unless the gem is version locked in `Gemfile` then you will get upgraded without warning.
