### ISSUE TITLE
Files page errors when upgrading from 1.12.2 to 1.12.3 

### ISSUE THREAD

**Issue by lyneux** [comfy/comfortable-mexican-sofa#559]
I've just upgraded from 1.12.2 to 1.12.3 to get the lovely new file functionality. I added the extra Mime support line but was disappointed to find that the page doesn't render but I get the following error:

```
NoMethodError in Comfy::Admin::Cms::FilesController#index
```

Associated (snipped) trace in the logs:

```
NoMethodError (undefined method `per' for #<ActiveRecord::AssociationRelation::ActiveRecord_AssociationRelation_Comfy_Cms_File:0x007fa71684d130>):
  activerecord (4.0.3) lib/active_record/relation/delegation.rb:121:in `method_missing'
  activerecord (4.0.3) lib/active_record/relation/delegation.rb:68:in `method_missing'
  comfortable_mexican_sofa (1.12.3) app/controllers/comfy/admin/cms/files_controller.rb:11:in `index'
```

**Comment by GBH** [comment]
Fixed. You have will_paginate, CMS had kaminari. Going forward you can use either.
